---
server:
    install: '1'
    timezone: Europe/Moscow
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: {
      base_box: xenial64,
      hostname: jenkins.server,
      ip: 192.168.42.42,
      memory: '1024',
      sharedfolder: ./,
      useVagrantCloud: '1',
      syncType: nfs,
      }
nginx:
    install: '1'
    docroot: /vagrant
    servername: jenkins.server
